project:
  type: website
  output-dir: docs
  render:
    - "*.qmd"
    - "!tutorial/"
execute:
  freeze: auto

website:
  title: "Toy Examples"
  navbar:
    left:
      - href: 1_intro.qmd
        text: Home
      - 2_function_approximator.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true